### ISSUE TITLE
[Discuss]Do I have to worry about EAGAIN error?

### ISSUE THREAD

**Issue by catinred2** [zeromq/jeromq#236]
when error ocurrs the API ZMsg.send returns false  and ZMsg.recvMsg returns null. If the errorno is EAGAIN, the api would retry or do I have to worry about it in upper level?

**Comment by daveyarwood** [comment]
It looks like a ZMQException is raised if the socket has a non-zero errno, [but only if that errno is not EAGAIN](https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/ZMQ.java#L2595-L2601).

I think that means that we do have to explicitly handle EAGAIN.

I'm not too familiar with this -- an open question I have is under what circumstances is the errno set to EAGAIN?

**Comment by daveyarwood** [comment]
It's been 2-1/2 years since this issue was opened. From grepping through the code for EAGAIN, I see that as of now, we do handle errno being EAGAIN in some cases. For example, [Mailbox.recv will return null](https://github.com/zeromq/jeromq/blob/bb0428c4d16d6c6045de303d9a43ad39239704d3/src/main/java/zmq/Mailbox.java#L89-L94) if it encounters EAGAIN or EINTR.

Closing this issue for now, as I'm not aware of any issues related to EAGAIN in practice. Feel free to reopen or create a new issue if you observe any issues re: EAGAIN.
