### ISSUE TITLE
Socket.base() warns against using it for proxy, and does not offer alternative

### ISSUE THREAD

**Issue by virtuald** [zeromq/jeromq#277]
I'm struggling to find the right way to build a proxy such as the load balancing example in the ZMQ guide. In particular, most of the methods I've found use `ZLoop` or the `Poller`, and the only way to add things to them is by creating a `PollItem`. To create a `PollItem`, you need a `SocketBase` object, but the documentation for `Socket.base()` warns against using it for a custom proxy.

What then, is the proper way to create a custom proxy in JeroMQ? The answer to this should be added to the documentation for Socket.base(), as it seems to be the only way that's immediately obvious.

**Comment by virtuald** [comment]
Looking around some more, I see that there are two PollItem objects -- one inside of ZMQ, and the other on its own. Seems like there should be documentation on one of them that it shouldn't be used.

**Comment by daveyarwood** [comment]
The poller API has changed a bit since this issue was filed. Instead of creating PollItems objects, you use a ZContext to create a ZPoller.

I agree that JeroMQ documentation is a bit lacking, but at least the test suite and ZGuide examples can provide some guidance. In this case, the [lbbroker](https://github.com/zeromq/jeromq/blob/master/src/test/java/guide/lbbroker2.java) example is relevant.
