### ISSUE TITLE
Paranoid Pirate ClosedChannelException

### ISSUE THREAD

**Issue by eplumer** [zeromq/jeromq#408]
I am trying the combination of lpclient, ppqueue, and ppworker from the JeroMQ samples directory. 

When the client tries to reconnect to the server, that operation seems to succeed as expected from the guide. However, on the next pass through the client main loop, the call to poller.poll(REQUEST_TIMEOUT) throws a java.nio exception:

```
Exception in thread "main" zmq.ZError$IOException: java.nio.channels.ClosedChannelException
	at zmq.ZMQ.poll(ZMQ.java:627)
	at org.zeromq.ZMQ$Poller.poll(ZMQ.java:1805)
	at com.pav.dataset.gateway.lpclient.main(lpclient.java:43)
Caused by: java.nio.channels.ClosedChannelException
	at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:197)
	at zmq.ZMQ.poll(ZMQ.java:624)
	... 2 more
```

At this point, the server/queue is still cycling through its polling loop normally.

_EDIT: code formatting - @daveyarwood_

**Comment by eplumer** [comment]
Forgot to mention, this is on head of master. v0.3.6 tag works correctly.  The method for creating the poller changed recently in this example.

**Comment by daveyarwood** [comment]
This seems like a bug in the lpclient example code. When there is no response from the server, the client socket is destroyed and re-created, however the poller is still using the original socket that was registered to the poller on line 30.

I would advocate for not destroying and re-creating the socket... I'm not convinced that it's necessary to do that.

@eplumer: Would you mind trying a couple of modifications to lpclient.java and reporting the results?

1. Remove lines 69-74 so that the same client socket is reused across requests.

2. Leave lines 69-74 in, but move lines 29-31 (where the poller is initialized and the client socket registered) inside of the while loop, so that a new poller is used each time, with the current iteration of the client socket registered.

**Comment by eplumer** [comment]
Test #1 Change

`                } else {
                    System.out.println("W: no response from server, retrying\n");
//                    //  Old socket is confused; close it and open a new one
//                    ctx.destroySocket(client);
//                    System.out.println("I: reconnecting to server\n");
//                    client = ctx.createSocket(ZMQ.REQ);
//                    client.connect(SERVER_ENDPOINT);
//                    //  Send request again, on new socket
                    client.send(request);
`
Generates this new exception

`Exception in thread "main" org.zeromq.ZMQException: Errno 156384763 : Operation cannot be accomplished in current state
	at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:1474)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1324)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1294)
	at com.pav.dataset.gateway.lpclient.main(lpclient.java:75)`

Test #2  Change

`        int sequence = 0;
        int retriesLeft = REQUEST_RETRIES;
        while (retriesLeft > 0 && !Thread.currentThread().isInterrupted()) {
            //  We send a request, then we work to get a reply
            String request = String.format("%d", ++sequence);
            client.send(request);

            int expect_reply = 1;
            while (expect_reply > 0) {
              
                Poller poller = ctx.createPoller(1);
                poller.register(client, Poller.POLLIN);

                //  Poll socket for a reply, with timeout
                int rc = poller.poll(REQUEST_TIMEOUT);
                if (rc == -1)
                    break;          //  Interrupted
`

Generates no exceptions, println traces as expected.

**Comment by eplumer** [comment]
Regarding re-using the socket, it seems that one intent of this guide example was to show that the "brute force" destroy/recreate approach was viable ... regardless of whether this might or might not be the best practice.

**Comment by daveyarwood** [comment]
I think the "Operation cannot be accomplished in current state" exception happened as a result of trying to send more than once without trying to receive in between. Thinking about this a little more, I think if the server doesn't respond after a reasonable timeout, then destroying and re-creating the socket is a decent idea after all because the new socket will be able to send a new request.

Seems like we should make the change to the lpclient example where we create a new poller each time we make a new socket. I don't like the fact that we accumulating pollers that way... I think we should expose a `destroyPoller` method to accompany `destroySocket`, and recommend that if you're going to destroy a socket, you should also destroy any pollers polling it.

I can make a quick PR to implement the above.

**Comment by daveyarwood** [comment]
Actually, a better thing to do here would be to re-use the same poller, but unregister the socket before destroying it, then register the new socket after it's created.

**Comment by daveyarwood** [comment]
See #409.

**Comment by daveyarwood** [comment]
I think this issue can be closed, as I fixed the examples.
