### ISSUE TITLE
Small issue with Maven package

### ISSUE THREAD

**Issue by burningalchemist** [zeromq/jeromq#434]
Hi Trevor!

Just pulled 0.4.0 package from Maven repository and noticed the following in the code:
```
public static final int ZMQ_VERSION_MAJOR = 3;
public static final int ZMQ_VERSION_MINOR = 2;
public static final int ZMQ_VERSION_PATCH = 5;
```
The same thing at [Javadoc](http://static.javadoc.io/org.zeromq/jeromq/0.4.0/constant-values.html#zmq.ZMQ.ZMQ_VERSION_MAJOR).

I don't see any problem at Github, though - 4.1.7 as it should be.
So to avoid any confusions could you please re-upload the package to Maven?

Kind regards,
Sergei

**Comment by trevorbernard** [comment]
Hi @burningalchemist, it would be great if you submitted a patch so we can release a new version of jeromq with this fix! I'd advise people not to re-upload maven artifacts since people depend on their functionality and are meant to be immutable. Even if the proposed change is as innocuous as this one.

**Comment by burningalchemist** [comment]
Got it, I will check and provide shortly. Thanks!

**Comment by trevorbernard** [comment]
Very nice
