### ISSUE TITLE
ZMQ.Socket class is final

### ISSUE THREAD

**Issue by SergueiEK** [zeromq/jeromq#446]
Hello

While migrating from 0.3.6 to the latest 0.4.2 I have noticed that ZMQ.Socket class has been changed to be final so I can't extend it any more by my custom Socket class. What was the reason behind that change? As far as I understand jeromq tries to mimic the jzmq API and it seems that making ZMQ.Socket class final breaks this contract.

Cheers,
Serguei

**Comment by trevorbernard** [comment]
It was added in the following commit when updating to be based on v4.1.17: https://github.com/zeromq/jeromq/commit/a55462b5#diff-ab533440049bba1d9014953971332f9aR405

We strive to maintain api compatibility with with JZMQ but it's getting more and more difficult as the code bases diverge. I would submit a pull request removing the final keyword from the Socket class.

**Comment by fredoboulo** [comment]
The rationales on this change were linked to more global ones:
- as fas as I can see, the code in the library relies much more on composition rather than on inheritance.
- I noticed that a lot a methods were public even if not needed, and lead to confusion, so the idea was to tight the code and making the class final was part of this process.

These may not be enough reasons, and I see no objection on loosening this constraint by removing the final keyword.
It was kind of expected to see some API breaks with such a big change, sorry for inconvenience. 
As for the compatibility with jzmq, I agree with Trevor that it is more and more difficult to guarantee full compatibility.

**Comment by sigiesec** [comment]
I think API compatibility in the sense that deriving from classes from either JeroMQ or jzmq is equivalent is a false promise that cannot be kept. To allow for this, jzmq and JeroMQ would need to specify constraints on their implementation details, most importantly on when they call into their own public methods. Maybe they do not right now, but is this part of the specification?
  
In the long-term, I think it would be a good idea to agree between JeroMQ and jzmq on a common API consisting of interfaces and maybe some non-opaque data types, and to maintain this as a separate artifact.
