### ISSUE TITLE
Tests added to different issues

### ISSUE THREAD

**Issue by fredoboulo** [zeromq/jeromq#485]
This is not an issue, just a reminder that the following issues have been tested/fixed/clarified by the latest code.

#442: [tested here](https://github.com/zeromq/jeromq/blob/master/src/test/java/zmq/socket/reqrep/TestReqCorrelateRelaxed.java)
#408 : [tested here](https://github.com/zeromq/jeromq/blob/master/src/test/java/org/zeromq/ParanoidPiratServerWithLazyPiratClientTest.java#L435)
#353: specific lock for monitor has been introduced. No tests.
#338: [tested here](https://github.com/zeromq/jeromq/blob/master/src/test/java/org/zeromq/TestPushPullThreadedTcp.java#L149)
#335: [tested here](https://github.com/zeromq/jeromq/blob/master/src/test/java/org/zeromq/DealerDealerTest.java)
#334: [tested here](https://github.com/zeromq/jeromq/blob/master/src/test/java/org/zeromq/ReqRepTest.java#L131)
#303: [tested here](https://github.com/zeromq/jeromq/blob/master/src/test/java/org/zeromq/ReqRepTest.java#L104)
#296: [tested here](https://github.com/zeromq/jeromq/blob/master/src/test/java/org/zeromq/ZBeaconTest.java#L44)
#291: [tested here](https://github.com/zeromq/jeromq/blob/master/src/test/java/zmq/socket/pair/TestPairTcp.java#L102)
#286: impossible in java, needs to be set at OS level, as reported in the README.
#285: [tested here](https://github.com/zeromq/jeromq/blob/master/src/test/java/zmq/socket/pair/TestPairTcp.java#L46)
#275: did not appear for quite some time. Still suspects that Utils.findOpenPort() is not fully reliable.

IMO, the creators of the issues could check if it is representative of their problems, and we could give a grace period before closing them. But it is up to you, dear issues groomers :)

**Comment by daveyarwood** [comment]
Thanks, this is helpful! I'll make a pass through the issues and see if any of them can be closed. Wherever it makes sense to do so, I'll check in with the issue creators. Some of these issues are quite old and the issues may have been resolved by now.

**Comment by daveyarwood** [comment]
Alright, I've combed through the issues and for each issue, I either closed it a resolved or left a comment asking if the poster was still experiencing the issue using the latest version of JeroMQ.

As some of the issues are 1 or 2 years old, I expect we won't hear back from some of the original posters. If after a reasonable period has elapsed, we still haven't heard back on an issue, I think it makes sense to close the issue because we don't have confirmation that the issue currently exists using the latest version. If someone is still having an issue, they can of course file a new issue or (assuming it's the same issue) reopen an old one.
