### ISSUE TITLE
ZLoop should not destroy the context - 0.4.3 - IllegalMonitorStateException

### ISSUE THREAD

**Issue by kmualem** [zeromq/jeromq#505]
Hi Guys,

I opened this ticket due to the conclusions in #490 

I upgraded from 0.3.6 to 0.4.3 and got the following exception, upon application shutdown:

```
2017-11-22_16:24:17.21407 java.lang.IllegalMonitorStateException
2017-11-22_16:24:17.21408 at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
2017-11-22_16:24:17.21411 at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
2017-11-22_16:24:17.21412 at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
2017-11-22_16:24:17.21413 at zmq.Ctx.terminate(Ctx.java:259)
2017-11-22_16:24:17.21414 at org.zeromq.ZMQ$Context.term(ZMQ.java:357)
2017-11-22_16:24:17.21415 at org.zeromq.ZMQ$Context.close(ZMQ.java:426)
2017-11-22_16:24:17.21416 at org.zeromq.ZLoop.destroy(ZLoop.java:90)
2017-11-22_16:24:17.21417 at com.trustwave.swg.utilities.monitoring.MonitoringReactor.terminate(MonitoringReactor.java:219)
2017-11-22_16:24:17.21418 at com.trustwave.swg.utilities.monitoring.MonitoringReactor.run(MonitoringReactor.java:106)
```

The only change that I did while moving from 0.3.6 to 0.4.3 is to add the context to the reactor ZLoop constructor.

The order that I'm destroying the resources is:

1. Remove all pollers from the reactor (ZLoop)
2. destroy the reactor (org.zeromq.ZLoop.destroy())
3. destory the sockets by zContext.destroySocket(socket)
4. destroy the context.

The ZLoop destory() also destroy the context, **which is wrong of course**. 
In my case, I have multiple threads with shadow contexts and upon process shutdown, I'm closing all thread resources by the book, before closing the Context itself.
Can you please explain to me what is the motivation behind closing the underlying Context?
Is it a bug ?

It was suggested by @fredoboulo to omit step number 2, meaning not to all ZLoop destory()
I'll try it of course, but this is just a workaround and this bug should be fixed.

I have a general question regarding the usage of the same context in all ZLoop threads.
Is it safe to have multiple threads, each one with its ZLoop and inside the ZLoop, pollers use the same context?

@daveyarwood - Maybe you can help me with it? Or maybe someone else can answer this question...

I would like to replace the 0.3.6 with 0.4.3 in our production applications, in order to solve #440 (Hopefully) 

So this is very critical for me to understand what are the circumstances ...

Any help is appreciated!

_edit: stacktrace formatting - @daveyarwood_

**Comment by daveyarwood** [comment]
I'm also not too familiar with ZLoop, but I will try my best to help.

At first, I thought that the exception you're seeing is related to #502 (included in 0.4.3 release), which introduced locks around things that are not threadsafe when closing a ZContext.

But then I realized, from looking closer at the stacktrace, that the ZLoop.destroy() call is closing the underlying ZMQ.Context directly, thus circumventing the changes we made to improve termination of a ZContext.

The exception you're seeing is being thrown [here](https://github.com/zeromq/jeromq/blob/v0.4.3/src/main/java/zmq/Ctx.java#L259) during the Ctx.terminate() call, specifically while trying to unlock the lock on `slotSync`. I believe this is happening because another thread is trying to terminate the context simultaneously.

Related SO question/answer: https://stackoverflow.com/questions/16884061/why-am-i-getting-illegalmonitorstateexception

If my understanding is correct, we are handling ZContext termination more safely thanks to #502, but that doesn't help in cases like this, where the underlying ZMQ.Context is closed directly. So, we are back to worrying about making sure a context is not closed from multiple threads simultaneously.

It is not clear to me why ZLoop closes the context. My intuition is that it should not do that, as we typically close the context directly at the end of a ZMQ program. From [this commit](https://github.com/zeromq/jeromq/commit/a55462b5dba1a61f28f32500a551038b4f3269a2) it looks like @fredoboulo added this bit where the ZLoop closes the context, so maybe he has some context on why we might want to do that?

**Comment by daveyarwood** [comment]
@kmualem BTW, manually destroying the sockets is not necessary when you're using a ZContext. ZContext.destroy() does that for you.

**Comment by daveyarwood** [comment]
This may just be my perspective, but I feel like it should only be necessary to run ZContext.destroy() to clean up, and the context should manage all of the things that need to be closed for you. I'm pretty sure it doesn't work that way, though.

**Comment by fredoboulo** [comment]
It was part of the huge commit that I made to upgrade to 4.1.7; it mostly slipped my attention, the code reviews and so on. This line should not be present as the ZLoop is not creating the context, and the destroy method of ZLoop shall be turned back to no-op.

**Comment by fredoboulo** [comment]
The only benefit that I see from that bug is that it is also putting the spotlight on the fact that ZContext is not thread-safe, which is weird and would need more investigation.

**Comment by daveyarwood** [comment]
If I'm understanding correctly, I think that (at least, as far as I'm aware) both the ZMQ.Context and the ZContext are thread-safe. It's just that the way we handle things with the ReentrantLocks, we throw an exception if a second thread tries to terminate a context that's already being terminated.

I'm trying to work out in my mind if that's a decent way to handle it or not. I think it probably is, because the second thread would want to know that it wasn't able to terminate the context because some other thread already has a lock on closing it. The logical conclusion, then, would be to figure out why multiple threads are trying to close the context and fix the calling code so that the context is closed only once -- like we're doing here.

Maybe it would provide a better user experience if we caught this exception and wrapped it in a friendlier one that indicates the context is already being closed?

**Comment by fredoboulo** [comment]
That's my understanding as well for thread-safety of contexts. But this demonstrates a different behaviour.

Let's try to tackle this down, shall we?

@kmualem could you provide a unit test that demonstrates the problem?

**Comment by kmualem** [comment]
@fredoboulo @daveyarwood - Thanks for helping. I think that I have now a better understanding of the problem and I would like to share it with you.

First, I'll try to explain my application destroy logic...
The main thread creates a ZContext and then share it with other threads by ZContext.shadow
The main thread also keeps control socket, inproc, that I use in order to send some commands to other threads, like destory command.
In each thread, I use ZLoop with handlers and the implementation of the control socket handler is to return -1 in case of a destory command (to stop the ZLoop). Then in the same thread, in the finally block, I have the "close resource" logic that I wrote in my first comment of the ticket.

When the shutdown hook is called on the main thread, I'm sending a "destroy" command to the other threads and wait X sec to the thread to stop.  (BTW, I wrote it like this because I didn't find a better way to close the resources)

```
try {
   thread.join(TimeUnit.SECONDS.toMillis(10));
   thread.interrupt();
} catch () {
...
}  finally {
  // close other resources
  zcontext.destory
}
```
So first, @daveyarwood  is correct, I got the IllegalMonitorStateException when trying to close the zcontext from the main thread, after It sent an interruption to the other thread.
But, the interesting part is that after I changed the join to wait forever thread.join(), It hangs on the following line in zmq.Ctx
```
//  Wait till reaper thread closes all the sockets.
Command cmd = termMailbox.recv(WAIT_FOREVER);
```

I guess that the underlying context is in use by other sockets, so the termination didn't work properly.
Anyway, I think that the ZLoop should not close the context... It gets the ZContext in the constructor and probably the ZContext is owned by other thread that doesn't expect this behavior.

What do you think?

**Comment by daveyarwood** [comment]
I think not having the ZLoop close the context should at least fix the immediate issue with the IllegalMonitorStateException.

**Comment by kmualem** [comment]
Can you please consider fixing it for the next release?

**Comment by daveyarwood** [comment]
Absolutely -- it looks like @fredoboulo has a fix in the works.
