### ISSUE TITLE
ClosedSelectorException when polling indefinitely and poller is closed before context is closed

### ISSUE THREAD

**Issue by javaJake** [zeromq/jeromq#580]
By following these steps I am able to reliably crash JeroMQ with a ClosedSelectorException:

1. Create a ZContext and a ZMQ.Poller in a try-with-resource block.
2. Create a socket and add it to the poller with POLLIN.
3. Create a thread that uses the poller to poll(-1).
4. Wait for the thread to start.
5. Return on the main thread so the try-with-resource triggers close() calls.

Here's the test (the sleep is there just to be extra sure it crashes; it crashed reliably without the sleep on my machine):
```java
import org.zeromq.ZContext;
import org.zeromq.ZMQ;
import org.zeromq.ZMQException;

public class Test {

	public static void main (String[] args) throws Exception {
		try (final ZContext context = new ZContext(1);
		     final ZMQ.Poller topPoll = context.createPoller(1)) {
			ZMQ.Socket pairSocket = context.createSocket(ZMQ.PAIR);

			topPoll.register(pairSocket, ZMQ.Poller.POLLIN);

			new Thread(() -> {
				try {
					topPoll.poll(-1);
				} catch (ZMQException e) {
					e.printStackTrace();
				}
			}).start();
			// May not be necessary
			Thread.sleep(100);
		}
	}
}
```

I get the following exception:
```
Exception in thread "Thread-0" java.nio.channels.ClosedSelectorException
	at sun.nio.ch.SelectorImpl.keys(SelectorImpl.java:68)
	at zmq.ZMQ.poll(ZMQ.java:722)
	at org.zeromq.ZMQ$Poller.poll(ZMQ.java:3210)
	at Test.lambda$main$0(Test.java:16)
	at java.lang.Thread.run(Thread.java:748)
```

The workaround is to never close Poller's, but to let the ZContext clean them up as it closes. Then, the fix from this pull request https://github.com/zeromq/jeromq/pull/390 triggers and handles the exception for us.

**Comment by daveyarwood** [comment]
I think part of the issue here might be that you are sharing a socket between threads.

From what I've read, ZMQ sockets are not thread-safe.

**Comment by daveyarwood** [comment]
...Actually, you are sharing a poller between threads. It's not really clear to me whether or not pollers are thread-safe, but I would guess not because they interact with sockets.

I think the overall idea is that the context manages the sockets (and pollers), so you don't want to give another thread access to those things because they belong to the context, and it's hard for the thread to know when the context has been terminated because it's running separately.

**Comment by javaJake** [comment]
So what is the correct way to break the indefinite poll() at that point? Close the context?

**Comment by daveyarwood** [comment]
That's a good question, and I'm not 100% certain what the recommended solution is. I've seen [this](https://github.com/zeromq/jeromq/wiki/Sharing-ZContext-between-thread) about using a "shadow context" to share contexts between threads. So maybe one way to do it is to make a shadow context for the other thread, and use the shadow context to make the poller. Then the idea is that when the original context is closed, the shadow context will close too, thus freeing up the poller.

Thoughts from others welcome here... there are gaps in my knowledge about using JeroMQ when working with multiple threads.

**Comment by fredoboulo** [comment]
Hi,

thanks for the report of the issue!

I cannot talk about THE correct way to do it, but may talk about what is done in ZActor, which uses a poller in a separate thread.
It follows what Dave was referencing: a shadow context. Without entering too much into technical details, a control pipe is created (inproc) with two sockets: one on the separate thread, one on the thread you want to control the behaviour with. Then the poller is registered with that socket. When a specific message is received from that control pipe, the poller exits from poll() and then the code can exit gracefully. I would finally send a message back into the pipe so that after reception, the context can be safely closed.

There are several API to do so: either a ZActor (will provide everything you need), or a ZThread that will create this control pipes for you (and a shadow context under the hood), and then you can code your poller logic.

Anyhow, it seems we can just catch the ClosedSelectorException while polling and directly return -1, but I would not recommend the usage of your test: sockets are not thread-safe and their usage (even closing) should be restricted to 1 thread only.
