### ISSUE TITLE
Too many open files on Linux

### ISSUE THREAD

**Issue by imkcy9** [zeromq/jeromq#700]
I create a SUB socket and connected to a unexist address, it seems to try to reconnect to this address again and again but not close the files.  I entered lsof command and saw the number of files is increased.  How can I fix this bug?

**Comment by fredoboulo** [comment]
Hi, which version of jeromq are you using?

**Comment by fbacchella** [comment]
Is that this one: #678

**Comment by imkcy9** [comment]
> Hi, which version of jeromq are you using?

0.5.0

**Comment by imkcy9** [comment]
> Is that this one: #678

That's it, thanks a lot!!!!

**Comment by trevorbernard** [comment]
@imkcy9 I would try v0.5.1 as it contains a potential fix to this issue

**Comment by piddubnyi** [comment]
Had the same problem.
Confirm it is fixed in 0.5.1

With 0.5.0:
# sudo ls "/proc/26095/fd" | wc -w
5388
[11:28:38]
# sudo ls "/proc/26095/fd" | wc -w
7218
[11:28:43]
# sudo ls "/proc/26095/fd" | wc -w
21506

With 0.5.1:
[11:36:12]
# sudo ls "/proc/32054/fd" | wc -w
228
[11:42:20]
# sudo ls "/proc/32054/fd" | wc -w
228

**Comment by trevorbernard** [comment]
awesome news
