### ISSUE TITLE
Problem: CI integration is flakey and should be revisitied

### ISSUE THREAD

**Issue by trevorbernard** [zeromq/jeromq#780]
The majority of CI builds fail. We have an integration on both travis-ci and circleci. We should choose only one going forward.

**Comment by fbacchella** [comment]
That's two different problems. If too much fails, it's not CI fault. Are the failure the same on both ?

**Comment by fbacchella** [comment]
Did you try to separate build and tests ? During build I run with: `MAVEN_OPTS: "-Xmx2048m"` but during tests, `MAVEN_OPTS: "-Xmx512m"`and `mvn ... -DargLine="-Xmx2048m"`
Older JVM and containers are not good friend, and JVM heuristic often fails in this context.

**Comment by somdoron** [comment]
@trevorbernard I started using github actions and pretty happy, it is fast and stable. I can make a pull request to transition to github actions if you want.

**Comment by trevorbernard** [comment]
@fbacchella No I haven't tried separating the build and tests. It's worth a shot. @somdoron how does github actions compare to travis or circleci? I'm way out of the loop

**Comment by somdoron** [comment]
Very similar to travis ci, a bit faster. However, travis ci supports more versions of java and android at the moment. I have no experience with circle.

**Comment by fbacchella** [comment]
My last try of a build using circleci:
- by defining the bootclass path, the project can be build using the latest JDK, but still run flawless in JDK8.
- parallel and efficient build (not re-compiling for each jdk).
- adding a android lint, not tested because the provided JDK is openjdk.
- static analysis using sonar cloud.

Code coverage is actually broken, but I fixed it in another project, so I just need to merge the fix.

It's in this branch: https://github.com/fbacchella/jeromq/tree/publishin2

**Comment by trevorbernard** [comment]
Would happily merge that PR 💯

**Comment by fbacchella** [comment]
I'm working on it. I have one question. I would like to remove Eclipse stuff in the pom, and push the checkstyle plugin in an optional profile. So it would only be used during CI and for people that want to check their code. What do you think about it ?

**Comment by trevorbernard** [comment]
Go for it. It likely came from me but I don't know what my intent was with it.

**Comment by trevorbernard** [comment]
CircleCi integration is working and Travis-Ci has been removed.
